# Generated by Django 5.0 on 2023-12-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200725_2336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAuthentication',
        ),
    ]
